# Generated by Django 4.0 on 2022-01-23 11:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('buckets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('front', models.TextField(max_length=256, verbose_name='Front-face')),
                ('back', models.TextField(max_length=256, verbose_name='Back-face')),
                ('streak', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'Archived'), (1, 'Active'), (2, 'Completed')], default=1)),
                ('confidence', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Fair'), (1, 'Poor')])),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buckets.bucket')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created_by', to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
